//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snoopy.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SnoopyDatabaseEntities : DbContext
    {
        public SnoopyDatabaseEntities()
            : base("name=SnoopyDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AnimalType> AnimalType { get; set; }
        public DbSet<PublisherType> PublisherType { get; set; }
        public DbSet<SAnimal> SAnimal { get; set; }
        public DbSet<SPublisher> SPublisher { get; set; }
    }
}
